Console/ConfigureWebsitePrefixes.php
edit your website prefixes by executing command: - php bin/console uvdesk:configure-prefixes
uvdesk/community-skeleton#126
=> Configure your website prefixes with command line

FileSystem/FileSystem.php
**Issue** #237
**invalid base url for file icon** 
- Append server's script name fetched from request's server parameter bag  to the attachment base path
- Remove index.php from the script name in the case of asset icon path
=> Attachments path fixes.

Controller/Thread.php, Services/TicketService.php
**Issue** #195
**cc user/collaborator reply via email not update into ticket**
- Make sure that active user is not null before calling methods on it in Ticket Service around line 1306.
- Execute the same workflow for thread type **_forward_** as for thread type _**reply**_
=> CC/BCC User/Collaborator reply via email not update into ticket 

Resources/views/ticketList.html.twig
Whenever an agent or admin tries to search the ticket from TicketList on the basis of a filter the result will take the broken image with their name.
After these changes, Admin & agent get the profile image with their name in the search option.
https://github.com/uvdesk/core-framework/issues/327
=> broken image code fix

Controller/EmailSettingsXHR.php
As we updated in email setting , it will updated the "UVdesk.yaml"  & set Customer & member prefix default value
It will take the value as string and check if it is null then only default values set .
https://github.com/uvdesk/community-skeleton/issues/399
=> member&customer prefix updates

Resources/views/Reports/listAgentActivities.html.twig
when filter agent in search option in report agent-profile image broked .
the image wil get the proper url and it will not broked again.
https://github.com/uvdesk/core-framework/issues/365
=> Broken image in reports search filter

Controller/SwiftMailer.php, Services/EmailService.php
Swiftmailer & mailbox passwords are saved without encryption & it will not good for security.
This will save your swift mailer password in encryption form. 
Encryption is important because it allows you to securely protect data that you don't want anyone else to have access to
Also, it will resolve the issue of special characters taken in password
https://github.com/uvdesk/community-skeleton/issues/429
https://github.com/uvdesk/community-skeleton/issues/276
=> changes for save password encryption in swiftmailer.yaml

Services/TicketService.php, Services/UserService.php
Before the admin changes the time stamp but was not show Accordingly.
It will show the time in formate which is set by admin in branding section.
=> changes for time stamp

Services/UserService.php
If a customer wants to set their timestamp with their need. They can't set now.
It will help customers to set their timestamp as per their needs.
=> changes for timestamp for user side

Resources/views/login.html.twig
whenever an admin & agent try to log in with new credentials it will not shows the messages in translate form
This will help to get the "invalid credentials" error in the translation form 
https://github.com/uvdesk/community-skeleton/issues/450
=> changes for translation error message "Invalid credentials"

Controller/Ticket.php
1. Why is this change necessary?
For now, if the admin or agent want to download attachments it gives a getThread() error
2. What does this change do, exactly?
After the change in ticket.php, it will be easy to download the single attachment or zip attachment
3. Please link to the relevant issues (if any).
=> chnages for zip attachment downloads

Controller/Thread.php, Services/EmailService.php
As we forward a thread it will send a mail to that agent or person for now it will send HTML tags in emails && In email templates if we choose a ticket.lastCollaboratorName & Email always returns null.
For now it will not send Html tags in email & Also fixed for ticket.lastCollaboratorName & Email 
https://github.com/uvdesk/core-framework/issues/428
=> forward message format issue & ticket.lastCollaboratorName & Email fix 

Services/EmailService.php
If we create a workflow with a note added to it then it will add that note in place of the message 
After the update the code If that is a note or not it will not be added a note in place of the message
https://github.com/uvdesk/core-framework/issues/433
=> Added note for manual create workflow & it will send the note in email reply

Resources/views/dashboard.html.twig, Resources/views/ticket.html.twig, Resources/views/tickets/quick-actions/saved-replies.html.twig, Services/EmailService.php
If a user has a long list of saved replies then he/she have to find & select it manually, so that's the reason that is so hattic some time
This will resolve the issue to find email saved replies by search box & also updated code for some fixes like version updated
=> Updates for new search bar feature on saved replies & also fixes of some issues

Services/EmailService.php
This will not provide any value to 'ticket.threadMessage' & 'ticket.message'.
Now, After updating the code it will provide the first thread message if No value is there.
https://github.com/uvdesk/core-framework/issues/443
=> changes for ticket.message & ticket.threadMessage value 

Services/UserService.php
If a customer didn't select any custom field then also, sidebar shows to the customer
After adding a check on customerSinnpet if it is not finding any custom filed then it is not showing sidebar
=> chnages for custom filed show on customer side if not selected

Repository/ThreadRepository.php, Services/EmailService.php, Workflow/Actions/Ticket/MailAgent.php, Workflow/Actions/Ticket/MailCustomer.php
If the reference Id is missing no reply is added to the ticket & create a new ticket.
Added message-id to reference id if reference ids missing in the header then compare to in-reply-to.
https://github.com/uvdesk/community-skeleton/issues/478
=> Email replies cause new ticket thread => fixed

Controller/Ticket.php, Resources/views/Snippets/createMemberTicket.html.twig
If an admin/agent creates a ticket for the customer then the formate of the message is not correct. Also signature is not added on reply & ticket create 
we add editor on the form so that it will count spaces & the next line. Also added signature on ticket create.
https://github.com/uvdesk/community-skeleton/issues/510
=> Operator Ticket creation issues V1.0.18 #510

Dashboard/NavigationTemplate.php
Uvdesk users see reports first instead of tickets.
position swapping of reports & tickets.
=> Dashboard sidebar ticket icon before reports

Services/FileUploadService.php
Image contains XSS payload, For security purpose hacker can take the information.
Fixed.
https://github.com/uvdesk/core-framework/issues/494
=> update for .svg contain XSS payload

Controller/Account.php, Services/TicketService.php, Services/UVDeskService.php
Mass ticket deletes not working.
Fixed.
https://github.com/uvdesk/core-framework/issues/518
https://github.com/uvdesk/core-framework/issues/517
https://github.com/uvdesk/core-framework/issues/515
https://github.com/uvdesk/core-framework/issues/514
=> Mass ticket deletes issue

PreparedResponse/Actions/Ticket/UpdateType.php, Resources/views/Snippets/createMemberTicket.html.twig, Resources/views/ticket.html.twig, Resources/views/ticketList.html.twig, Workflow/Actions/Ticket/UpdateType.php, composer.json
Updated ticket types listing in alphabetical order on ticket create form on admin panel and also now showing ticket type name instead of description.
[#527 ](https://github.com/uvdesk/community-skeleton/issues/527)
https://github.com/uvdesk/support-center-bundle/issues/191
https://github.com/uvdesk/support-center-bundle/issues/190
https://github.com/uvdesk/support-center-bundle/issues/185
https://github.com/uvdesk/support-center-bundle/issues/175
=> List ticket types in alphabetical order and display ticket type name instead of description

Resources/views/ticket.html.twig
**Changes for DateTime format on the admin ticket view page on header and ticket information**
**Please link to the relevant issues (if any):**
**Issue No:** https://github.com/uvdesk/core-framework/issues/594
=> Changes for Datetime format on the admin ticket view page on header and ticket information
