uvdesk/core-framework

Controller/Ticket.php
Repository/TicketRepository.php
Resources/views/ticketTypeAdd.html.twig
Resources/views/ticketTypeList.html.twig
Services/TicketService.php

Ticket Type Validation for adding the same ticket type name again, and replace code with name(textual change in list and add).

ticket type validation for name and other textual change

---

Controller/SavedReplies.php
Resources/views/ticketList.html.twig
Services/TicketService.php

1. Change the color to colorCode in ticketList.html .  
2. For pop up functionality made changes in ticket service query for getting the short info about ticket.
3. Save Reply redirection wrong link change and in delete operation remove and add correct variable.

ticketList.html.twig change color to colorCode.

---

Controller/Account.php
Controller/Customer.php
Controller/Thread.php
Controller/Ticket.php
Repository/TicketRepository.php
Resources/views/Templates/header.html.twig
Resources/views/ticket.html.twig

commit 1.   Image validation added for customer, agent and user profile update.
commit 2.   header search bar removed some unnecessary item and added required once. 
commit 3.   Added Validation (customer name character only) for  customer update  and changed 
numbering for submit action in the ticket view. Set  submit status ticket in thread.php . 
removed non defined(getAgentPartialDetailById) method in Ticket repository and added the 
correct one.
commit 4.  Added Next and previous buttons in ticket view.

Profile image validation add for customer agent and user profile

---

Controller/Thread.php

1.  Ticket status set for different submit actions in  thread.php  when a reply created.

Added By default status open for ticket when reply

---

Controller/SavedReplies.php
Controller/Ticket.php
Resources/config/routes/tickets.yaml
Resources/views/Agents/createSupportAgent.html.twig
Resources/views/Agents/updateSupportAgent.html.twig
Resources/views/Customers/createSupportCustomer.html.twig
Resources/views/Customers/updateSupportCustomer.html.twig
Resources/views/Snippets/createMemberTicket.html.twig
Resources/views/Templates/tinyMCE.html.twig
Resources/views/savedReplyForm.html.twig
Resources/views/ticket.html.twig

1. Saved Reply body message validation added.
2. Image Upload link removed from text editor.
3. Added validation for email in ticket, customer and agent to stop xss.
4. Task removed from ticket view.
5. Added icons for zip, doc, and unknown source. and download option for every attachment.

saved reply body message validation added

---

PreparedResponse/Actions/Ticket/MailAgent.php
Resources/views/ticket.html.twig
Resources/views/ticketList.html.twig
Workflow/Actions/Ticket/MailAgent.php

1. Ticket list sorting as per ticket id, last replied etc. And added some more option for ticket attachment icons.
2. Added two more option for mail to agent dropdown in workflow and prepared response. (Me and Assigned agent).

Ticket list sorting resolve and added some more formats for attachments

---

Controller/Ticket.php
Controller/TicketXHR.php
FileSystem/DefaultManager.php
Repository/TicketRepository.php
Resources/views/resetPassword.html.twig
Resources/views/templateForm.html.twig
Resources/views/ticket.html.twig
Services/EmailService.php
Services/UserService.php
Templates/Email/Resources/Agent/TicketReply.php
Workflow/Actions/Agent/TransferTickets.php

1. Transfer ticket action added  in  agent  actions when creating Workflow.
2. Agent reply to customer ticket, removed  footer from email template.
3. Default option  (not assigned) in team and group drop down for assigning a team and group to ticket removed from ticket view page.
4. In Email template  Placeholder as per selection of ticket or user will show. 
5. Ticket count  (link) customer in ticket view. so that customers can see all created tickets by them.
6. On customer mail ticket link added by which customer can reach to that ticket. And added differentiate link for customer and agent ticket view. 
7. Extension of uploaded file added at the end, whenever saving that image. so that we can get required icon as per uploaded document.
8. Reset Password validation and submission.

Transfer ticket action added in workflow.

---

Controller/Ticket.php
Controller/TicketXHR.php
Fixtures/HelpdeskBranding.php
Repository/TicketRepository.php
Resources/config/doctrine/Website.orm.yml
Resources/public/css/_uikit.css
Resources/views/Templates/lightskin.html.twig
Resources/views/Templates/sidebar.html.twig
Resources/views/ticketList.html.twig
Services/TicketService.php
Services/UserService.php

1- Website default logo
2- now customer will receive mail whether it is created from knowledgebase panel or member panel (uvdesk/community-skeleton#56)
3- ticket's team or group can be not assigned (uvdesk/community-skeleton#84)
4- correct counting of tabs in tickets section (uvdesk/community-skeleton#91 uvdesk/community-skeleton#63)
5- ticket list mass action according to permission of that agent (uvdesk/community-skeleton#93)
6- customer will be active, when created via mail (#28 )
7- agent can be added as a collaborator in ticket

fixed issues

---

Controller/Ticket.php
Resources/config/routes/public.yaml
Resources/views/Agents/createSupportAgent.html.twig
Resources/views/Agents/updateSupportAgent.html.twig
Resources/views/Customers/createSupportCustomer.html.twig
Resources/views/Customers/updateSupportCustomer.html.twig
Resources/views/account.html.twig
Resources/views/profile.html.twig
Resources/views/supportTagList.html.twig
Resources/views/ticket.html.twig
Resources/views/ticketList.html.twig
Services/EmailService.php

1. Removed last name required validation from customer, agent, admin profile.
2. Sorting of ticket tag by ticket count. (#26 )
3. Search Filter for tag , label, group and team in ticket.php.
4. added icons for  doc, zip and other fields.

sorting tag by ticket count, last name validation removed, search filter added for tag, label, team, group.

---

Repository/ThreadRepository.php
Resources/views/ticket.html.twig
Services/TicketService.php

1. At the time of update thread if we paste a image in text editor  without any text then a message shows this field is mandatory even a image is present in editor. resolved this issue.
2. Thread filter utf8_decode added for thread message  for customer panel.
3. "No result found" adding was adding on tag and labels. resolved.
4. Issue:  #35

update thread mandatory  condition even after content. resolved

---

Services/MailboxService.php

Attachments in threads that were pasted in the reply section will be visibile in thread section in ticket

Attachments in thread

---

Controller/Thread.php
Repository/ThreadRepository.php
Repository/TicketRepository.php
Resources/views/templateForm.html.twig
Resources/views/ticket.html.twig
Services/TicketService.php

1.Email template issue and content issue in 1st message.
2. thread update problem with image resolve at admin panel.
3. At customer panel attachment issue and pagination for view ticket.
4. issue: uvdesk/support-center-bundle#25
5. Removed next and previous from TicketRepositorry.

Email Template and content issue admin at first ticket created.

---

Services/TicketService.php

1. Removed some sources which are used to filter ticket but not yet in our system like facebook, ebay etc.
2. issue: #60

Removed some sources from filter which are not present yet.

---

Controller/Swiftmailer.php
Controller/Ticket.php
Controller/TicketXHR.php
Package/UVDeskCoreConfiguration.php
Repository/SavedRepliesRepository.php
Repository/SupportGroupRepository.php
Repository/SupportPrivilegeRepository.php
Repository/SupportTeamRepository.php
Repository/TicketRepository.php
Repository/UserRepository.php
Resources/config/routes/members.yaml
Resources/views/Swiftmailer/swiftmailerAdd.html.twig
Resources/views/Swiftmailer/swiftmailerEdit.html.twig
Resources/views/Swiftmailer/swiftmailerList.html.twig
Services/TicketService.php
Services/UVDeskService.php

1. Ticket type with status active will show in type drop down in ticket.
2. issue : #65
3. Swiftmailer add, update, delete functionality added.
4. ticket filter issue by saved filter issue: #67 
5. Trim all the values before  searching.

Ticket type with status active will only show with type drop down in ticket.

---

Package/Composer.php
Templates/swiftmailer.yaml

1. Default template for Swift Mailer added.

Default Swift Mailer Config with comment spool and url

---

Controller/SwiftMailer.php
Controller/SwiftMailerXHR.php
Resources/config/routes/members.yaml
Resources/views/Swiftmailer/createMailer.html.twig
Resources/views/Swiftmailer/settings.html.twig
Resources/views/Swiftmailer/updateMailer.html.twig

1. Textual changes in views, member.yaml route correction and swiftmailer.xhr  and swiftmailer.php check for if mailer exist.

Texual change for swiftmailer views and member.yaml change

---

Resources/views/Swiftmailer/createMailer.html.twig
Resources/views/templateForm.html.twig
Resources/views/ticketList.html.twig

1. Swift Mailer With no space validation added.
2. When no ticket in list multi select checkbox will not show.
3. issue : #75, #74, #73, #72

Checkbox hide when no ticket and Swiftmailer white space validation.

---

Resources/public/css/_uikit.css

Assets will be visible in production mode

assets issue in production mode

---

Controller/SwiftMailer.php

1. Swift Mailer  file  changes.

Swiftmailer.php  file change.

---

Repository/TicketRepository.php
Resources/public/css/_uikit.css
Resources/public/js/_common.js
Resources/views/Snippets/createMemberTicket.html.twig
Resources/views/forgotPassword.html.twig
Services/TicketService.php

uvdesk/community-skeleton#107
uvdesk/community-skeleton#104
uvdesk/core-framework#67
uvdesk/core-framework#63

resolved issues

---

Services/TicketService.php
Services/UserService.php

1. Added some function in service to check if block spam exist before creating the ticket from customer panel.
2. issue: #108

Added some functions in ticket and user service for block spam functionality.

---

Repository/EmailTemplatesRepository.php
Resources/views/profile.html.twig
Resources/views/ticket.html.twig
Services/TicketService.php

1. Console error resolved in ticket view.
Issue : #113

Ticket view console error resolved

---

Services/TicketService.php
Workflow/Actions/Ticket/MailGroup.php

1. In ticket service replace utf-8 by html_entity_decode.
2. workflow action mail to group changes.
2. issue: #112, #123

Ticket service changes and workflow action mail to group changes 

---

Resources/views/ticket.html.twig
Services/TicketService.php
Workflow/Actions/Ticket/UpdateAgent.php

Checking current user agent Instance

Checking current user agent Instance

---

Resources/views/ticket.html.twig
Services/TicketService.php
Services/UserService.php

Signature and popular article added

Article at front end

---

Extension/TwigExtension.php
Resources/config/services.yaml

unknown addslashes in twig issue

---

Controller/EmailSettingsXHR.php
Controller/SwiftMailer.php
Controller/Ticket.php
Resources/public/css/_custom.css
Resources/public/js/_common.js
Resources/views/forgotPassword.html.twig
Services/UVDeskService.php
SwiftMailer/SwiftMailer.php
Templates/uvdesk.php

**1. Changed style to bold in sidebar for active sidebar option**
**issue** - https://github.com/uvdesk/core-framework/issues/140
Function in service is altered to revert back array with 'isActive' key with 'true' value for current active component. 
**2. Swiftmailer can not be created with same mailer ID**
**issue**: https://github.com/uvdesk/mailbox-component/issues/14
Function is altered to throw exception when same mailer ID is used to create/update swiftmailer configuration.
**3. emoving static site url with dynamic current site url**
**issue** - uvdesk/mailbox-component#13
Static site url was included in template file for generating uvdesk.yaml file, changed it with dynamic current site url.
**4. Meaningful error/warning message.**
**issue** - …

mailbox-component issue-13

---

Controller/EmailSettingsXHR.php
Resources/views/Templates/header.html.twig
Services/UVDeskService.php

**1. Fixing prefix for customer and member panel.**
**issue** - https://github.com/uvdesk/mailbox-component/issues/24
Updating uvdesk.php template file once prefix is set through web installer.
**2. Site url updated.**
**issue** - https://github.com/uvdesk/mailbox-component/issues/13
Update Site url in uvdesk.yaml file.
**3. Email-settings from search bar.**
**issue** - https://github.com/uvdesk/core-framework/issues/142
Adding Email settings to be searched by search bar.

Fixing prefix for customer and member panel.

---

Controller/SwiftMailer.php
Controller/TicketXHR.php
Repository/TicketRepository.php
Resources/public/js/_common.js
Resources/views/SwiftMailer/manageConfigurations.html.twig
Resources/views/Templates/sidebar.html.twig
Resources/views/ticket.html.twig
Services/TicketService.php
Services/UVDeskService.php

**1. Timezone feature added for Super Admin.**
**issue** - https://github.com/uvdesk/community-skeleton/issues/164
Timezone setup option is added into branding section and its changes are reflected on ticket panel.
**2. Side bar menu is fixed for low resolution window.**
**issue** - https://github.com/uvdesk/community-skeleton/issues/104
Sidebar will not remain hidden in low resolution window.
**3. Side menu bar update.**
**issue** - https://github.com/uvdesk/core-framework/issues/140
Sidebar menu showing multiple active menu.
**4. Swiftmailer transport on update fixed.**
**issue** - https://github.com/uvdesk/mailbox-component/issues/22

Timezone Feature and issues

---

Fixtures/WelcomeTicket.php

welcome ticket fixture added

---

Resources/public/css/_uikit.css
Resources/public/js/_common.js
Resources/views/Templates/header.html.twig

**1. Opensource layout update.**
Changes as per requirement.

Opensource layout update

---

EventListener/Swiftmailer.php
Resources/public/css/_custom.css
Resources/views/Email/emailSettings.html.twig
Resources/views/Templates/header.html.twig

**1. CSS update.**
**2. Banner logo link updated.**
**issue-** https://github.com/uvdesk/community-skeleton/issues/179
**3. dropdown none selected.**
**issue -** https://github.com/uvdesk/mailbox-component/issues/35
**4. Event listener add for updating uvdesk.yml file.**
Event listener is added to update uvdesk.yml file if the selected swiftmailer id is updated/deleted.

Updates in layout

---

Controller/EmailSettingsXHR.php
Controller/TicketXHR.php
Repository/TicketRepository.php
Resources/public/css/_uikit.css
Resources/views/Email/emailSettings.html.twig

1.Customer status active when added as a collaborator.
issue: https://github.com/uvdesk/core-framework/issues/164#issuecomment-512709829

Customer status active when added as a collaborator.

---

Controller/Account.php
Controller/Authentication.php
Entity/User.php
Resources/views/Agents/updateSupportAgent.html.twig

**issue** #197 
- removed unique=true from User entity
- added request data instead of true in form submit.
**issue** #202 
- Customer can not reset his/her password through Agent panel unless registered as agent
- Agent can not reset his/her password through Customer panel unless registered as customer
**issue** #203 
- logged in user can not disable his account
- checkbox change event
- update isEnabled only if it has changed

Error with update users - SQL Unique constraint

---

Resources/views/Templates/header.html.twig

**1. Filter added for 'create-ticket' access.**
**issue:** https://github.com/uvdesk/support-center-bundle/issues/66

Misc. changes

---

Services/UserService.php

Pull request for Issue #177, enabling Timezone function for UserService.php.

Issue 177 - Added getTimeZone() to UserService.php

---

Controller/Account.php
Controller/Thread.php
Controller/Ticket.php
README.md
Resources/views/ticket.html.twig
composer.json

Now agent image show in place of customer image on create initial ticket by agent on behalf of customer

fix initial thread user image in ticket view page

---

Dashboard/AsideTemplate.php
Dashboard/HomepageTemplate.php
FileSystem/FileSystem.php
Services/EmailService.php
UIComponents/Dashboard/Homepage/Items/Tags.php
Workflow/Actions/Ticket/MailAgent.php
Workflow/Actions/Ticket/MailCustomer.php

**Issue** #54 
**Attachment's are not received on agent's mail**
- Passing thread attachments MailAgent workflow action
- Added getBasePath method to FileSystem for getting server's base path
- Processing attachments array in EmailService to proivde a different name for email attachments
**Issue** #59 
**Mails not received by forward mail to / CC / BCC users when add into ticket**
- Added a switch statement to send mail based on thread type
**Issue** #208 
**Customer not receive ticket reply mail if attachment were added to ticket**
- same as issue issue #54 
**Issue** #213 
**Shift tags under productivity section**
- Sorting asidebar items alphabatically
- Re-placing the user section below Knowledge section
- Moving Tags Section Item to Productivity section

Misc. Fixes

---

Controller/Thread.php
Controller/Ticket.php
Resources/public/css/_uikit.css
Resources/views/ticket.html.twig
Resources/views/ticketList.html.twig
Services/TicketService.php

#216 #217 
created new service  getTicketAccess  to check privileges for ticket access by agent behalf of ticket access level .
#119  change in list item font-size 
#75 fix the  initial thread user image behalf of createdby  in ticket.html.twig file
#209 mail not received by customer when note  added on ticket by agent

1.0 misc issues

---

Resources/views/Templates/attachment.html.twig
Services/TicketService.php
Templates/config.yaml
Templates/twig.yaml
Templates/uvdesk.php

**Issue** #29
**File attachment limit exceed**
- Added attachment constraints parameters inside config.yaml and uvdesk.php
- Added twig global variables referring the container parameters inside twig.yaml
- Added front-end validation in attachment.html.twig
- Refactored Ticket service's _isTicketAccessGranted_ method

Attachments validation

---

Repository/ThreadRepository.php

#234 customer image shown instead of agent image because user type customer is set in thread data,
now changed the static user type customer  with dynamic user-type on thread.

1.0- issue #234 

---

Resources/views/dashboard.html.twig

URL correction

---

.github/ISSUE_TEPLATES/Bug_report.md
.github/ISSUE_TEPLATES/Feature_request.md
.github/ISSUE_TEPLATES/Support_question.md
.github/PULL_REQUEST_TEMPLATE.md
.github/SECURITY.md

created issue, pull request and security templates

templates 

---

Controller/Thread.php
PreparedResponse/Actions/Agent/MailAgent.php
PreparedResponse/Actions/Ticket/MailAgent.php
Workflow/Actions/Agent/MailAgent.php
Workflow/Actions/Ticket/MailAgent.php
Workflow/Actions/Ticket/MailCustomer.php

Resolve forword issue when forwording ticket due to undefined variable.

Resolve forword issue when forwording ticket due to undefined variable 

---

Services/EmailService.php

https://github.com/uvdesk/core-framework/issues/306#issue-656346881

Fix incorrect email headers

---

UIComponents/Dashboard/Search/Apps.php
UIComponents/Dashboard/Search/Articles.php
UIComponents/Dashboard/Search/Categories.php
UIComponents/Dashboard/Search/Customers.php
UIComponents/Dashboard/Search/Folders.php

when Agent has privileges of Knowledgebase & Customer. it is very easy for him/her to search from the search tab 
Adding of this file is able to search some more options like customer, articles, categories & folders.
https://github.com/uvdesk/core-framework/issues/329

Adding missing files in core-framework/UIComponents/Dashboard/Search directory 

---

Controller/Report.php
Repository/TicketRatingRepository.php
Resources/config/routes/private.yaml
Resources/views/Reports/kudos-insights.html.twig
Services/ReportService.php
Services/UserService.php
UIComponents/Dashboard/Homepage/Items/Kudos.php
UIComponents/Dashboard/Panel/Items/Reports/Kudos.php
UIComponents/Dashboard/Search/Kudos.php

This is a new Feature in Opensource Uvdesk -> Kudos is all about the ratings of an agent's profiles
This change is all about the ratings of an agent's profiles whether they have got a good response or the bad one from the customers.  It also displays whether the agent is a  star performer or a mediocre one

Adding Features of Kudos

---

Controller/Thread.php
Resources/views/Groups/createSupportGroup.html.twig
Resources/views/ticket.html.twig
Workflow/Actions/Ticket/MailCustomer.php

**1. Users Image not displaying properly in Group and Team Section**
https://github.com/uvdesk/core-framework/issues/388
**2. Collaborator on email is coming wrong format** 
https://github.com/uvdesk/core-framework/issues/387
**3. Collaborator name is coming wrong on ticket thread at agent ticket view** 
https://github.com/uvdesk/core-framework/issues/386
**4. collaborator reply are not being added into ticket** 
https://github.com/uvdesk/core-framework/issues/358

issue fix uvdesk open source

---

Services/EmailService.php
Workflow/Actions/Ticket/MailCustomer.php

This will show  a flash message if the swift mailer is not working
This will alert you that your mail is not sending. 
https://github.com/uvdesk/community-skeleton/issues/401

add flash when swiftmailer not working

---

Controller/Account.php
Resources/public/css/_uikit.css

[Bug](https://github.com/uvdesk/core-framework/issues/403).
[Enhancement](https://github.com/uvdesk/support-center-bundle/issues/118).

Remove from customer side image so default image not showing in Tickets thread

---

Controller/Thread.php
Workflow/Actions/Ticket/MailAgent.php
Workflow/Actions/Ticket/MailCustomer.php

This will make a single BCC send mail & also it will check if getCC is null or not 
It will help Single BCC to send mail & also able to send a mail with CC or collabrator
https://github.com/uvdesk/core-framework/issues/420
https://github.com/uvdesk/core-framework/issues/419

update for mail to BCC

---

Controller/Ticket.php
Workflow/Actions/Ticket/MailAgent.php
Workflow/Actions/Ticket/MailCustomer.php

This change will help to send mail to send single BCC, CC && Collaborators, Also collaborator reply then it will be added to the thread.
When there is no group assign then also the agent able to open the ticket
This change will help to send mail to send single BCC, CC && Collaborators, Also collaborator reply then it will be added to the thread.
When there is no group assign then also the agent able to open the ticket
https://github.com/uvdesk/core-framework/issues/418
https://github.com/uvdesk/core-framework/issues/410
https://github.com/uvdesk/core-framework/issues/409

Updates for multiples Collaborator reply added to thread , Also assign agent able to view ticket

---

Controller/Ticket.php
Services/CustomFieldsService.php
Services/TicketService.php

1. Why is this change necessary?
FormBuilder package not fully support new version Opensouce Uvdesk
2. What does this change do, exactly?
This will help Formbuilder to support new Latest version Opensouces Uvdesk
3. Please link to the relevant issues (if any).

update for formbuilder support

---

Resources/views/Snippets/createMemberTicket.html.twig

contain a wrong value in the placeholder (cf).
update the value of the placeholder (cf).

update for placeholder value contain wrong value

---

Controller/Account.php

https://github.com/uvdesk/community-skeleton/issues/506
Profile picture remove from physical path as well if deleted from admin panel from profile section.

Profile picture remove from physical path as well if deleted.

---

PreparedResponse/Actions/Agent/MailAgent.php
PreparedResponse/Actions/Ticket/MailGroup.php
Workflow/Actions/Agent/MailAgent.php
Workflow/Actions/Ticket/MailAgent.php
Workflow/Actions/Ticket/MailCustomer.php

=> Creating a Prepared Response after being assigned to any group then applying Prepared responses showing error.
=> When ticket created from Gmail side with adding inline images showing error
=> Added object to entity 
=> Inline images show raw content remove
https://github.com/uvdesk/core-framework/issues/475
https://github.com/uvdesk/core-framework/issues/476

issues 476/475 resolved

---

Resources/views/Snippets/createMemberTicket.html.twig
Services/UserService.php

resize not added to the editor
resize added to the editor

editor resize issue

---

Controller/Account.php
Controller/Customer.php
Repository/UserRepository.php
Resources/views/Agents/listSupportAgents.html.twig
Resources/views/Agents/updateSupportAgent.html.twig
Resources/views/Customers/listSupportCustomers.html.twig
Resources/views/Customers/updateSupportCustomer.html.twig

Agent or customer disable on the same time issue. If we disable an agent then the customer automatically disables it.
Now, If a customer or agent disable his profile then only the current role profile has gone disabled.
https://github.com/uvdesk/core-framework/issues/489

update for agent & customer disable on same time => resolved

---

Services/EmailService.php

ticket thread message containing note message in an email response.
fixed.
https://github.com/uvdesk/core-framework/issues/488

ticket.threadMessage containing note in email response

---

Controller/Ticket.php

Page not found exception not working properly.
add NotFoundHttpExeption in place of Excepton
https://github.com/uvdesk/core-framework/issues/487

updates for Exception => NotFoundHttpException

---

Workflow/Actions/Ticket/MailAgent.php

Not able to send mail to an assigned agent.
fixed.

updates for email on assigne agent not send

---

Resources/views/Agents/updateSupportAgent.html.twig

The agent was able to change "Account owner" to "Administrator" or "Agent".
Fixed.
https://github.com/uvdesk/core-framework/issues/520

agent was able to change "Account owner" to "Administrator" or "Agent".

---

Repository/TicketRepository.php
Resources/public/js/_common.js
Resources/views/Agents/createSupportAgent.html.twig
Resources/views/Templates/layout.html.twig
Resources/views/Templates/sidebar.html.twig
Resources/views/templateList.html.twig
Services/CustomFieldsService.php
Services/UVDeskService.php
Templates/config.yaml

side bar not responded on page reload & on resize page
Change the icon on page resize & also able to open or close the page

side bar fliker issue

---

Services/TicketService.php
Services/UserService.php

Changes for custom-field app

---

Workflow/Actions/Ticket/AddNote.php
Workflow/Actions/Ticket/MailGroup.php
Workflow/Actions/Ticket/MailLastCollaborator.php
Workflow/Actions/Ticket/MarkSpam.php

Fixes for workflow ticket actions issue

---

Resources/views/Templates/layout.html.twig

**Added viewport initial-scale in layout.html.twig file** 
**Please link to the relevant issues (if any):**
https://github.com/uvdesk/core-framework/issues/621

Added viewport initial-scale in layout.html.twig file

---

Controller/AccountXHR.php

**Changes for agent deleted issue #604**
=> Please link to the relevant issues (if any):
https://github.com/uvdesk/core-framework/issues/604

Resolve issue while deleting agent from dashboard

---

Resources/views/Snippets/createMemberTicket.html.twig

Please link to the relevant issues (if any)
https://github.com/uvdesk/core-framework/issues/629

Add message field validation while creating tickets

---

Resources/views/Snippets/createMemberTicket.html.twig
Resources/views/Templates/layout.html.twig
composer.json

Please link to the relevant issues (if any)
https://github.com/uvdesk/core-framework/issues/612

In arebic  language added RTL(Right To Left) position on admin side 
